# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: terminal 1
  - init: npm init
    command: npm run start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 19002
    onOpen: open-preview
